server:
  port: 30000

eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST_IP}"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://139.150.75.239:8761/eureka

spring:
  application:
    name: alarm-distribution-service

kafka:
  bootstrap:
    servers: 10.7.27.17:9092,10.7.27.18:9092,10.7.27.19:9092